from datetime import date
from almond import Almond
from duck import Duck
from goat import Goat
from llama import Llama
from turtle import Turtle
from horse import Horse
from cow import Cow
from chicken import Chicken
from copperhead import CopperHead
from rattlesnake import RattleSnake
from cobra import Cobra
from electric_eel import Electric_Eel
from python_snake import Python_Snake
from goose import Goose
from swan import Swan
from bass import Bass
